---
version: '2.2'

services:
  db:
    image: postgres:10.6
    container_name: postgres_db
    command: -c fsync=off -c full_page_writes=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      APP_DB_USER: admin
      APP_DB_PASS: admin
      APP_DB_NAME: users
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 5432:5432

  spring:
    build: ""
    image: igivanov1728/auth-spring:latest
    environment:
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://localhost:5432/users
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
